"""initial schema

Revision ID: 9d17275688c3
Revises: 
Create Date: 2026-06-21 11:55:18.261524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d17275688c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('broker_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mt5_login', sa.BigInteger(), nullable=False),
    sa.Column('mt5_password', sa.Text(), nullable=False),
    sa.Column('server', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('master', 'slave', 'standalone', name='accounttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broker_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broker_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('copier_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_account_id', sa.Integer(), nullable=False),
    sa.Column('slave_account_id', sa.Integer(), nullable=False),
    sa.Column('lot_multiplier', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['master_account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slave_account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copier_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copier_links_master_account_id'), ['master_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_copier_links_slave_account_id'), ['slave_account_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=False),
    sa.Column('mt5_ticket', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trade_type', sa.Enum('buy', 'sell', name='tradetype'), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='tradestatus'), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_account_id', 'mt5_ticket', name='uq_trade_account_ticket')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_broker_account_id'), ['broker_account_id'], unique=False)

    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_per_lot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', name='commissionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commissions_broker_account_id'), ['broker_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commissions_trade_id'), ['trade_id'], unique=True)

    op.create_table('copier_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copier_link_id', sa.Integer(), nullable=False),
    sa.Column('master_ticket', sa.BigInteger(), nullable=False),
    sa.Column('slave_account_id', sa.Integer(), nullable=False),
    sa.Column('slave_ticket', sa.BigInteger(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['copier_link_id'], ['copier_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slave_account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copier_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copier_mappings_copier_link_id'), ['copier_link_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copier_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copier_mappings_copier_link_id'))

    op.drop_table('copier_mappings')
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commissions_trade_id'))
        batch_op.drop_index(batch_op.f('ix_commissions_broker_account_id'))

    op.drop_table('commissions')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_broker_account_id'))

    op.drop_table('trades')
    with op.batch_alter_table('copier_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copier_links_slave_account_id'))
        batch_op.drop_index(batch_op.f('ix_copier_links_master_account_id'))

    op.drop_table('copier_links')
    with op.batch_alter_table('broker_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broker_accounts_user_id'))

    op.drop_table('broker_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
